### ISSUE TITLE
Issue.issue_name not returned

### ISSUE THREAD

**Issue by Buried-In-Code** [Metron-Project/mokkari#29]
**Describe the bug**
The Issue schema doesn't have issue_name marked as optional, however Metron doesn't always return this field and it doesn't raise an exception.

**To Reproduce**
1. Make a call to `result = session.issue(_id=39505)`
2. Try and access the issue_name field: `result.issue_name`
3. An AttributeError is raised:
> AttributeError: 'Issue' object has no attribute 'issue_name'

**Expected behavior**
It should either raise an exception or the field be Optional

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by bpepple** [comment]
Looking at this more closely, I don't think this is really a bug. It **is** raising an `AttributeError` for a field that doesn't exist. It would raise the same error if you accessed: `result.foo_bar`, which is correct.

Where this should be addressed most likely is in the documentation since the `issue_name` field is **only** used for list results, since the detail views contains the information need to create the issue name (`series_name`and `number` fields).

**Comment by Buried-In-Code** [comment]
Ah right I see, good to know.
